config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('poll.urls', namespace='poll')),
    # path('', include('pages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    # path('', HomePageView.as_view(), name='home'),
    # path('about/', AboutPageView.as_view(), name='about'),
]

poll/urls.py
from django.urls import path

from .views import create_view, list_view, update_view, delete_view, export_to_pdf

app_name = 'poll'

urlpatterns = [
    path('', list_view, name='list'),
    path('create/', create_view, name='create'),
    path('update/<id>/', update_view, name='update'),
    path('delete/<id>/', delete_view, name='delete'),
    path('pdf/<id>/', export_to_pdf, name='pdf'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email

pages/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models
from django.forms import ModelForm
from model_utils import Choices


# Create your models here.

class Person(models.Model):
    SEX_CHOICES = Choices('M','F')

    name = models.CharField(max_length=250)
    age = models.IntegerField(blank=True)    
    sex = models.CharField(choices=SEX_CHOICES, default=SEX_CHOICES.M, max_length=1)
    personal_information = models.TextField(max_length=500, blank=True)
    education_level = models.CharField(max_length=150, blank=True)
    body_weight = models.FloatField()

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

poll/forms.py
from django.forms import ModelForm
from .models import Person


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

poll/views.py
import io
import reportlab
from django.http import FileResponse
from reportlab.pdfgen import canvas
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)
from django.shortcuts import render
from .forms import PersonForm
from .models import Person


# Create your views here.


def create_view(request):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    form = PersonForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")

    context['form'] = form
    return render(request, "poll/create_view.html", context)


def list_view(request):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["dataset"] = Person.objects.all()

    return render(request, "poll/list_view.html", context)


# after updating it will redirect to detail_View


def detail_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["data"] = Person.objects.get(id=id)

    return render(request, "poll/detail_view.html", context)

# update view for details


def update_view(request, id):
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(Person, id=id)

    # pass the object as instance in form
    form = PersonForm(request.POST or None, instance=obj)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")

    # add form dictionary to context
    context["form"] = form

    return render(request, "poll/update_view.html", context)


# delete view for details
def delete_view(request, id):
    context = {}

    obj = get_object_or_404(Person, id=id)

    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect("/")

    return render(request, "poll/delete_view.html", context)


def export_to_pdf(request, id):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    person_objt = Person.objects.get(pk=id)

    p.drawCentredString(250, 745, 'Nombre: ' + str(person_objt.name))
    p.drawCentredString(250, 730, 'Edad: ' + str(person_objt.age))
    p.drawCentredString(250, 715, 'Sexo: ' + str(person_objt.sex))
    p.drawCentredString(250, 700, 'Nivel Educacional: ' +
                        str(person_objt.education_level))
    p.drawCentredString(250, 685, 'Peso corporal: ' +
                        str(person_objt.body_weight))
    p.drawCentredString(250, 670, 'Informacion: ' +
                        str(person_objt.personal_information))

    p.showPage()
    p.save()

    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='document_poll.pdf')

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<title>{% block title %}DjangoX{% endblock title %}</title>
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

{% block css %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}
</head>

<body>
  <main role="main">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{% url 'poll:list' %}">Encuestas</a>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.email }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </nav>
    </div>
  </main>

  <div class="container">
    {% block content %}
      <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>



  {% block javascript %}
  <!-- Bootstrap JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  <!-- 3rd party JavaScript -->

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>
</html>

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="DjangoX logo"/>
  <p class="lead">A Django starter project with batteries.</p>
</div>
{% endblock content %}

templates/poll/create_view.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Poll{% endblock title %}

{% block content %}

<form method="POST" enctype="multipart/form-data"> 
    <div class="form-group">
        <!-- Security token -->
        {% csrf_token %}
    
        <!-- Using the formset -->
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" >Salvar</button>
    </div>
</form>
{% endblock content %}

templates/poll/delete_view.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete Poll{% endblock title %}

{% block content %}
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>
{% endblock content %}

templates/poll/list_view.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Polls{% endblock title %}

{% block content %}
<div class="main">
    
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Edad</th>
            <th scope="col">Sexo</th>
            <th scope="col">Informacion</th>
            <th scope="col">Nivel de escolaridad</th>
            <th scope="col">Peso corporal</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
            {% for data in dataset %}
          <tr>
            <th>{{ data.name }}</th>
            <td>{{ data.age }}</td>
            <td>{{ data.sex }}</td>
            <td>{{ data.personal_information }}</td>
            <td>{{ data.education_level }}</td>
            <td>{{ data.body_weight }}</td>
            <td><a href="{% url 'poll:update' data.id %}">Editar</a>  <a href="{% url 'poll:delete' data.id %}">Eliminar</a>  <a href="{% url 'poll:pdf' data.id %}">pdf</a></td>
          </tr>
          {% endfor %}
          </tbody>
          </table>
          <br>
          <!-- <button type="button" class="btn btn-primary"> -->
              <a href="{% url 'poll:create' %}">Nueva encuesta</a>
            <!-- </button> -->
</div>
{% endblock %}

templates/poll/update_view.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Poll{% endblock title %}

{% block content %}

<form method="POST" enctype="multipart/form-data"> 
    <div class="form-group">
        <!-- Security token -->
        {% csrf_token %}
    
        <!-- Using the formset -->
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" >Actualizar</button>
    </div>
</form>
{% endblock content %}